// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int N=Integer.parseInt(args[0]), countBig=0, countSmall=0;
		double result,ratio;
		for(int i=1;i<=N;i++) {
			result=Math.random();
			if (result>0.5)
				countBig++;
			else countSmall++;
		}
		if (countSmall==0||countBig==0) {
			System.out.println(">0.5:"+" "+countBig);
			System.out.println("<=0.5:"+" "+countSmall);
			System.out.println("Ratio:"+" "+countBig+":"+countSmall);
		} else {
			ratio=(double)(countBig)/countSmall;
			System.out.println(">0.5:"+" "+countBig);
			System.out.println("<=0.5:"+" "+countSmall);
			System.out.println("Ratio:"+" "+ratio);
		}
	}
}
